from __future__ import annotations

import pandas as pd
import plotly.graph_objects as go


_GWP_AXIS = (
    "Kumulierte THG-Emissionen 2025 - 2075<br>"
    "[kg<sub>CO2eq</sub>/m<sup>2</sup><sub>BGF</sub>]"
)

_GWP_BANDS = (
    {"name": "L3", "y0": 195, "y1": 320, "color": "#CFDCE0"},
    {"name": "L2", "y0": 70, "y1": 195, "color": "#93B9C6"},
    {"name": "L1", "y0": 0, "y1": 70, "color": "#73A8BB"},
)


def darken_color(hex_color: str, factor: float = 0.7) -> str:
    """Return a darker hex color for Plotly pattern foregrounds."""
    value = (hex_color or "").strip().lstrip("#")

    if len(value) == 3:
        value = "".join(c * 2 for c in value)

    if len(value) != 6:
        return "#000000"

    try:
        r, g, b = (int(value[i:i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        return "#000000"

    r, g, b = (max(0, int(v * factor)) for v in (r, g, b))
    return f"#{r:02x}{g:02x}{b:02x}"


def _marker(series: dict, *, replace_pattern: bool = False) -> dict:
    """Build a Plotly marker dictionary from materialized series metadata."""
    color = series.get("color") or "#cccccc"
    pattern = series.get("pattern") or ""
    marker = {"color": color}

    if color.lower() == "#ffffff":
        marker["line"] = {"color": "gray", "width": 1}

    if pattern:
        marker["pattern"] = {
            "shape": pattern,
            "fgcolor": darken_color(color),
            "bgcolor": color,
            **({"fillmode": "replace"} if replace_pattern else {}),
        }

    return marker


def _role(series: dict) -> str:
    """Return the normalized semantic role of a materialized series."""
    return str(series.get("role") or "").strip().casefold()


def _series_for_role(report: dict, role: str) -> list[dict]:
    """Return report series matching one semantic chart role."""
    role = role.strip().casefold()
    return [series for series in report["series"] if _role(series) == role]


def _values(report: dict, series: dict, *, absolute: bool = False) -> list[float]:
    """Return numeric values for one materialized report series."""
    values = pd.to_numeric(
        report["frame"][series["var_name"]],
        errors="coerce",
    ).fillna(0.0)

    if absolute:
        values = values.abs()

    return values.tolist()


def _empty_chart(report: dict, message: str) -> go.Figure:
    """Return an empty Plotly figure with an explanatory annotation."""
    fig = go.Figure()
    fig.add_annotation(
        text=message,
        x=0.5,
        y=0.5,
        xref="paper",
        yref="paper",
        showarrow=False,
    )
    fig.update_layout(
        title=report.get("title") or report.get("chart_name"),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        xaxis={"visible": False},
        yaxis={"visible": False},
    )
    return fig


def render(report: dict) -> go.Figure:
    """Render one materialized PEExcel report as a Plotly figure.

    Supported chart types are the canonical values generated by the active
    PEExcel reporting schema.
    """
    chart_type = str(report.get("chart_type") or "").strip()

    if not report.get("series"):
        return _empty_chart(
            report,
            f"Keine Serien für Diagramm '{report.get('chart_name')}'.",
        )

    if chart_type == "stacked_bar_comparison":
        return _stacked_bar_comparison(report)

    if chart_type == "build_gwp_chart":
        return _gwp(report)

    if chart_type == "build_four_column_gwp_chart":
        return _gwp_four_column(report)

    if chart_type == "build_multi_grid_chart":
        return _multi_grid(report)

    raise ValueError(
        f"Unsupported Plotly chart type {chart_type!r} "
        f"for chart {report.get('chart_name')!r}"
    )


def _stacked_bar_comparison(report: dict) -> go.Figure:
    """Render Bedarf and Deckung as paired stacked bars for each scenario."""
    fig = go.Figure()
    variants = report["frame"]["Variant"].tolist()

    groups = (
        ("Bedarf", _series_for_role(report, "Bedarf")),
        ("Deckung", _series_for_role(report, "Deckung")),
    )

    for group_name, series_list in groups:
        x = [variants, [group_name] * len(variants)]

        for series in series_list:
            values = _values(report, series, absolute=True)

            fig.add_trace(
                go.Bar(
                    name=series["label"],
                    x=x,
                    y=values,
                    marker=_marker(series),
                    text=values,
                    texttemplate="<b>%{y:.1f}</b>",
                    textposition="inside",
                    insidetextanchor="middle",
                    legendgroup=group_name,
                    legendgrouptitle_text=group_name,
                    hovertemplate=(
                        f"<b>{series['label']}</b><br>"
                        "Wert: %{y:.1f}<extra></extra>"
                    ),
                )
            )

    fig.update_layout(
        title=report["title"],
        barmode="stack",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        yaxis_title=report.get("unit") or "",
        xaxis={
            "tickangle": 0,
            "dividerwidth": 2,
            "dividercolor": "gray",
            "showgrid": False,
        },
        yaxis={
            "gridcolor": "gray",
            "griddash": "dot",
        },
        legend={
            "orientation": "v",
            "yanchor": "top",
            "y": 1,
            "xanchor": "left",
            "x": 1.02,
        },
        margin={"t": 50, "l": 50, "r": 150, "b": 50},
    )

    return fig


def _add_gwp_bands(fig: go.Figure, variants: list[str]) -> None:
    """Add the L1-L3 GWP reference bands used by the PEExcel charts."""
    if not variants:
        return

    for band in _GWP_BANDS:
        fig.add_hrect(
            y0=band["y0"],
            y1=band["y1"],
            fillcolor=band["color"],
            opacity=0.4,
            layer="below",
            line_width=0,
        )

        fig.add_trace(
            go.Bar(
                x=[[variants[0]], ["EE"]],
                y=[None],
                name=band["name"],
                marker={"color": band["color"]},
                showlegend=True,
            )
        )


def _gwp(report: dict) -> go.Figure:
    """Render the two-column embodied/operational GWP chart."""
    fig = go.Figure()
    variants = report["frame"]["Variant"].tolist()

    x_axis = [
        [variant for variant in variants for _ in (0, 1)],
        ["EE", "OE"] * len(variants),
    ]

    _add_gwp_bands(fig, variants)

    def add_group(role: str, is_oe: bool) -> None:
        for series in _series_for_role(report, role):
            values = []

            for value in _values(report, series):
                values.extend([0, value] if is_oe else [value, 0])

            fig.add_trace(
                go.Bar(
                    name=series["label"],
                    x=x_axis,
                    y=values,
                    marker=_marker(series, replace_pattern=True),
                    width=0.6,
                    hovertemplate=(
                        f"<b>{series['label']}</b><br>"
                        "Wert: %{y:.1f}<extra></extra>"
                    ),
                )
            )

    add_group("Baulich", False)
    add_group("Betrieblich", True)

    for series in _series_for_role(report, "Balance Variable"):
        values = _values(report, series)

        fig.add_trace(
            go.Scatter(
                name=series["label"],
                x=[variants, ["EE"] * len(variants)],
                y=values,
                mode="markers+text",
                marker={
                    "symbol": "diamond",
                    "color": series.get("color") or "#7B8E1D",
                    "size": 8,
                },
                text=[f"  {value:.1f}" for value in values],
                textposition="middle right",
            )
        )

    fig.update_layout(
        title=report["title"],
        barmode="relative",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        legend={
            "orientation": "v",
            "yanchor": "top",
            "y": 1,
            "xanchor": "left",
            "x": 1.02,
        },
        yaxis={
            "title": report.get("unit") or _GWP_AXIS,
            "autorange": True,
            "gridcolor": "gray",
            "griddash": "dot",
            "zerolinecolor": "gray",
            "zerolinewidth": 2,
        },
        xaxis={
            "type": "multicategory",
            "tickangle": 0,
            "dividercolor": "gray",
            "dividerwidth": 2,
            "showgrid": False,
        },
        margin={"l": 50, "r": 150, "t": 50, "b": 50},
    )

    return fig


def _gwp_four_column(report: dict) -> go.Figure:
    """Render the four-column embodied/operational GWP breakdown."""
    fig = go.Figure()
    variants = report["frame"]["Variant"].tolist()

    labels = [
        "Baulich",
        "Baulich kompensation",
        "Betrieblich",
        "Betrieblich kompensation",
    ]

    x_axis = [
        [variant for variant in variants for _ in range(4)],
        labels * len(variants),
    ]

    _add_gwp_bands(fig, variants)

    for column_index, role in enumerate(labels):
        for series in _series_for_role(report, role):
            values = []

            for value in _values(report, series):
                row = [0, 0, 0, 0]
                row[column_index] = value
                values.extend(row)

            fig.add_trace(
                go.Bar(
                    name=series["label"],
                    x=x_axis,
                    y=values,
                    marker=_marker(series, replace_pattern=True),
                    width=0.6,
                    hovertemplate=(
                        f"<b>{series['label']}</b><br>"
                        "Wert: %{y:.1f}<extra></extra>"
                    ),
                )
            )

    for series in _series_for_role(report, "Balance Variable"):
        values = _values(report, series)

        fig.add_trace(
            go.Scatter(
                name=series["label"],
                x=[variants, [labels[-1]] * len(variants)],
                y=values,
                mode="markers+text",
                marker={
                    "symbol": "diamond",
                    "color": series.get("color") or "#7B8E1D",
                    "size": 8,
                },
                text=[f"  {value:.1f}" for value in values],
                textposition="middle right",
            )
        )

    fig.update_layout(
        title=report["title"],
        barmode="relative",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        legend={
            "orientation": "v",
            "yanchor": "top",
            "y": 1,
            "xanchor": "left",
            "x": 1.02,
        },
        yaxis={
            "title": report.get("unit") or _GWP_AXIS,
            "autorange": True,
            "gridcolor": "gray",
            "griddash": "dot",
            "zerolinecolor": "gray",
            "zerolinewidth": 2,
        },
        xaxis={
            "type": "multicategory",
            "tickangle": 90,
            "dividercolor": "gray",
            "dividerwidth": 2,
            "showgrid": False,
        },
        margin={"l": 50, "r": 180, "t": 50, "b": 50},
    )

    return fig


def _multi_grid(report: dict) -> go.Figure:
    """Render a placeholder until multi-grid report metadata is defined."""
    return _empty_chart(
        report,
        "Multi-grid rendering is not implemented yet.",
    )

def chart(data, chart_name: str) -> go.Figure:
    """Materialize and render a standard PEExcel chart."""
    from pexl.reporting import materialize
    return render(materialize(data, chart_name))